import { readFileSync } from "fs";
import { join } from "path";
import { describe, expect, it } from "vitest";
import {
  buildHostedSaleFields,
  buildSigningBody,
  parseGatewayBody,
  phpCompatibleSort,
  signFields,
  verifySignedResponse,
  type TakepaymentsConfig,
} from "@/lib/payments/takepayments";

/**
 * GOLDEN TESTS — fixtures generated by running the OFFICIAL takepayments Node
 * SDK's Gateway.sign() (sdk-nodejs-takepayments.zip, gateway.js) over the same
 * inputs. Our port must match byte-for-byte: a signature mismatch at the
 * gateway means every payment fails, silently, at the worst moment. If these
 * fail after an edit to lib/payments/takepayments.ts, the port drifted — fix
 * the port, never the fixtures.
 */

interface Golden {
  name: string;
  secret: string;
  data: Record<string, string | number>;
  signature: string;
}

const golden: Golden[] = JSON.parse(
  readFileSync(join(__dirname, "takepayments-golden.json"), "utf8"),
);

const CONFIG: TakepaymentsConfig = {
  merchantId: "119837",
  signatureKey: "9GXwHNVC87VqsqNM",
  hostedUrl: "https://gw1.tponlinepayments.com/paymentform/",
  directUrl: "https://gw1.tponlinepayments.com/direct/",
  testMode: true,
};

describe("signFields — golden parity with the official SDK", () => {
  for (const g of golden) {
    it(g.name, () => {
      expect(signFields(g.data, g.secret)).toBe(g.signature);
    });
  }

  it("covers the nasty encodings (fixtures include CRLF, &, unicode, *, quotes)", () => {
    const names = golden.map((g) => g.name).join(" | ");
    expect(names).toContain("star");
    expect(names).toContain("CRLF");
  });
});

describe("buildSigningBody serialisation", () => {
  it("sorts keys PHP-style and encodes RFC1738 (space=+, *=%2A, ~ literal)", () => {
    const body = buildSigningBody({ b: "two words", a: "*~", c: 1 });
    expect(body).toBe("a=%2A~&b=two+words&c=1");
  });

  it("normalises every newline flavour to %0A", () => {
    const crlf = buildSigningBody({ x: "a\r\nb" });
    const cr = buildSigningBody({ x: "a\rb" });
    const lf = buildSigningBody({ x: "a\nb" });
    expect(crlf).toBe("x=a%0Ab");
    expect(cr).toBe("x=a%0Ab");
    expect(lf).toBe("x=a%0Ab");
  });

  it("phpCompatibleSort: shorter key wins, [ sorts as 0", () => {
    expect(phpCompatibleSort("a", "ab")).toBeLessThan(0);
    expect(phpCompatibleSort("a[b]", "a0b0")).toBe(0); // stops at bracket
  });
});

describe("verifySignedResponse", () => {
  const secret = "test-secret";

  it("accepts a correctly signed response and strips the signature", () => {
    const fields = { responseCode: "0", xref: "ABC123", amountReceived: "10000" };
    const signed = { ...fields, signature: signFields(fields, secret) };
    expect(verifySignedResponse(signed, secret)).toEqual(fields);
  });

  it("rejects a tampered amount", () => {
    const fields = { responseCode: "0", amountReceived: "10000" };
    const signed = { ...fields, signature: signFields(fields, secret), amountReceived: "1" };
    expect(verifySignedResponse(signed, secret)).toBeNull();
  });

  it("rejects a missing signature", () => {
    expect(verifySignedResponse({ responseCode: "0" }, secret)).toBeNull();
  });

  it("handles the partial form hash|field,list — only listed fields signed", () => {
    const all = { responseCode: "0", xref: "X1", unsignedExtra: "junk" };
    const signedSubset = { responseCode: "0", xref: "X1" };
    const sig = signFields(signedSubset, secret) + "|responseCode,xref";
    expect(verifySignedResponse({ ...all, signature: sig }, secret)).toEqual(all);
  });

  it("rejects a partial form whose hash doesn't match the listed fields", () => {
    const sig = signFields({ responseCode: "0" }, secret) + "|responseCode,xref";
    expect(verifySignedResponse({ responseCode: "0", xref: "TAMPERED", signature: sig }, secret)).toBeNull();
  });
});

describe("buildHostedSaleFields", () => {
  const built = buildHostedSaleFields({
    config: CONFIG,
    amountPence: 10000,
    transactionUnique: "row-uuid-1",
    orderRef: "MMR014 deposit",
    redirectUrl: "https://ops.marleymoves.co.uk/api/card/return",
    callbackUrl: "https://ops.marleymoves.co.uk/api/card/callback",
    customerName: "Freddy Arbuthnot",
    customerEmail: "freddy@example.com",
  });

  it("targets the hosted URL with a one-off ECOM SALE", () => {
    expect(built.url).toBe(CONFIG.hostedUrl);
    expect(built.fields.action).toBe("SALE");
    expect(built.fields.type).toBe("1");
    expect(built.fields.amount).toBe("10000");
    expect(built.fields.currencyCode).toBe("826");
  });

  it("NEVER includes recurring/CoF fields (hard policy: no stored credentials)", () => {
    const banned = ["rtAgreementType", "rtSequenceCount", "rtSequenceNumber", "cardNumber", "cardCVV"];
    for (const field of banned) expect(built.fields).not.toHaveProperty(field);
  });

  it("signature verifies with the same secret (round-trip)", () => {
    const { signature, ...rest } = built.fields;
    expect(signFields(rest, CONFIG.signatureKey)).toBe(signature);
  });

  it("all values are strings ready for hidden inputs", () => {
    for (const v of Object.values(built.fields)) expect(typeof v).toBe("string");
  });
});

describe("parseGatewayBody", () => {
  it("decodes x-www-form-urlencoded incl. + spaces and bracket keys", () => {
    const parsed = parseGatewayBody("responseCode=0&orderRef=Test+purchase&a%5Bb%5D=1");
    expect(parsed.responseCode).toBe("0");
    expect(parsed.orderRef).toBe("Test purchase");
    expect(parsed["a[b]"]).toBe("1");
  });
});
