/**
 * Cubic survey catalogue — every measurement from Connor's iMVE account
 * (extracted 2026-07-10, docs/imve-cubic-catalogue.json; audit in
 * docs/cubic-survey-audit.md). Values are CUBIC FEET per unit. Code-owned
 * (versioned + tested), with per-line overrides and custom items handled on
 * the survey itself — a Settings editor is deliberately deferred.
 */

export interface CubicCatalogueItem {
  /** Stable id: "<category-key>:<item-slug>". */
  key: string;
  title: string;
  ft3: number;
}

export interface CubicCategory {
  key: string;
  title: string;
  items: CubicCatalogueItem[];
}

export const CUBIC_CATEGORIES: CubicCategory[] = [
  {
    key: "living-space",
    title: "Living space",
    items: [
      { key: "living-space:sofa-2-seater", title: "Sofa 2 seater", ft3: 35 },
      { key: "living-space:sofa-3-seater", title: "Sofa 3 seater", ft3: 50 },
      { key: "living-space:sofa-4-seater", title: "Sofa 4 seater", ft3: 65 },
      { key: "living-space:corner-sofa-3-seater", title: "Corner sofa 3 seater", ft3: 103 },
      { key: "living-space:corner-sofa-4-seater", title: "Corner sofa 4 seater", ft3: 140 },
      { key: "living-space:sofa-bed", title: "Sofa bed", ft3: 50 },
      { key: "living-space:footstool", title: "Footstool", ft3: 6 },
      { key: "living-space:armchair-small", title: "Armchair small", ft3: 12 },
      { key: "living-space:armchair-medium", title: "Armchair medium", ft3: 15 },
      { key: "living-space:armchair-large", title: "Armchair large", ft3: 20 },
      { key: "living-space:armchair-recliner", title: "Armchair recliner", ft3: 17 },
      { key: "living-space:rocking-chair", title: "Rocking chair", ft3: 7 },
      { key: "living-space:sideboard-small", title: "Sideboard small", ft3: 12 },
      { key: "living-space:sideboard-medium", title: "Sideboard medium", ft3: 18 },
      { key: "living-space:sideboard-large", title: "Sideboard large", ft3: 25 },
      { key: "living-space:cabinet-small", title: "Cabinet small", ft3: 12 },
      { key: "living-space:cabinet-medium", title: "Cabinet medium", ft3: 20 },
      { key: "living-space:cabinet-large", title: "Cabinet large", ft3: 30 },
      { key: "living-space:welsh-dresser", title: "Welsh dresser", ft3: 80 },
      { key: "living-space:bookcase-small", title: "Bookcase small", ft3: 10 },
      { key: "living-space:bookcase-medium", title: "Bookcase medium", ft3: 18 },
      { key: "living-space:bookcase-large", title: "Bookcase large", ft3: 26 },
      { key: "living-space:ikea-kallax-4-cube", title: "Ikea kallax 4 cube", ft3: 8 },
      { key: "living-space:ikea-kallax-6-cube", title: "Ikea kallax 6 cube", ft3: 12 },
      { key: "living-space:kallax-8-cube", title: "kallax 8 cube", ft3: 16 },
      { key: "living-space:kallax-12-cube", title: "kallax 12 cube", ft3: 24 },
      { key: "living-space:kallax-16-cube", title: "kallax 16 cube", ft3: 32 },
      { key: "living-space:bureau", title: "Bureau", ft3: 18 },
      { key: "living-space:writing-desk", title: "Writing desk", ft3: 14 },
      { key: "living-space:dining-table-small", title: "Dining table small", ft3: 20 },
      { key: "living-space:dining-table-medium", title: "Dining table medium", ft3: 30 },
      { key: "living-space:dining-table-large", title: "Dining table large", ft3: 50 },
      { key: "living-space:dining-chairs", title: "Dining chairs", ft3: 5 },
      { key: "living-space:coffee-table", title: "Coffee table", ft3: 12 },
      { key: "living-space:small-side-table", title: "Small side table", ft3: 2 },
      { key: "living-space:nest-of-tables", title: "Nest of tables", ft3: 5 },
      { key: "living-space:hall-table", title: "Hall table", ft3: 14 },
      { key: "living-space:tv-32in", title: "TV 32in", ft3: 3 },
      { key: "living-space:tv-43in", title: "TV 43in", ft3: 4 },
      { key: "living-space:tv-52in", title: "TV 52in", ft3: 6 },
      { key: "living-space:tv-60in", title: "TV 60in +", ft3: 10 },
      { key: "living-space:tv-stand-medium", title: "TV stand medium", ft3: 5 },
      { key: "living-space:tv-stand-large", title: "TV stand large", ft3: 8 },
      { key: "living-space:tv-box-dvd-sky-etc", title: "TV box (DVD, Sky etc)", ft3: 2 },
      { key: "living-space:hifi-set", title: "Hifi set", ft3: 16 },
      { key: "living-space:hifi-speaker", title: "Hifi speaker", ft3: 5 },
      { key: "living-space:cd-tower", title: "CD tower", ft3: 6 },
      { key: "living-space:floor-standing-lamp-medium", title: "Floor standing lamp medium", ft3: 5 },
      { key: "living-space:floor-standing-lamp-large", title: "Floor standing lamp large", ft3: 10 },
      { key: "living-space:table-lamp", title: "Table lamp", ft3: 3 },
      { key: "living-space:picture-mirror-small", title: "Picture/mirror small", ft3: 1 },
      { key: "living-space:picture-mirror-medium", title: "Picture/mirror medium", ft3: 3 },
      { key: "living-space:picture-mirror-large", title: "Picture/mirror large", ft3: 5 },
      { key: "living-space:rug-medium", title: "Rug medium", ft3: 6 },
      { key: "living-space:rug-large", title: "Rug large", ft3: 12 },
      { key: "living-space:coat-stand", title: "Coat stand", ft3: 10 },
      { key: "living-space:shoe-rack", title: "Shoe rack", ft3: 2 },
      { key: "living-space:grandfather-clock", title: "Grandfather clock", ft3: 20 },
      { key: "living-space:piano-upright", title: "Piano upright", ft3: 70 },
      { key: "living-space:baby-grand-piano", title: "Baby grand piano", ft3: 80 },
      { key: "living-space:grand-piano", title: "Grand piano", ft3: 150 },
      { key: "living-space:piano-stool", title: "Piano stool", ft3: 4 },
      { key: "living-space:indoor-plant-small", title: "Indoor plant small", ft3: 2 },
      { key: "living-space:indoor-plant-large", title: "Indoor plant large", ft3: 5 },
      { key: "living-space:vacuum", title: "Vacuum", ft3: 4 },
      { key: "living-space:6ft-pool-table", title: "6ft pool table", ft3: 50 },
      { key: "living-space:2ft-fish-tank", title: "2ft Fish tank", ft3: 25 },
      { key: "living-space:3ft-fish-tank", title: "3ft Fish tank", ft3: 30 },
      { key: "living-space:4ft-fish-tank", title: "4ft Fish tank", ft3: 45 },
      { key: "living-space:sundry", title: "Sundry", ft3: 1 },
      { key: "living-space:storage-box", title: "Storage box", ft3: 6 },
      { key: "living-space:bags", title: "Bags", ft3: 3 },
      { key: "living-space:boxed-already", title: "Boxed already", ft3: 3 },
      { key: "living-space:medium-box", title: "Medium box", ft3: 2 },
      { key: "living-space:large-box", title: "Large box", ft3: 4 },
    ],
  },
  {
    key: "loft",
    title: "Loft",
    items: [
      { key: "loft:suitcases", title: "Suitcases", ft3: 5 },
      { key: "loft:sundry-cuft", title: "Sundry cuft", ft3: 1 },
      { key: "loft:boxed-already", title: "Boxed already", ft3: 3 },
      { key: "loft:medium-box", title: "Medium box", ft3: 2 },
      { key: "loft:large-box", title: "Large box", ft3: 4 },
    ],
  },
  {
    key: "bedrooms",
    title: "Bedrooms",
    items: [
      { key: "bedrooms:divan-bed-single-and-mattress", title: "Divan bed single and mattress", ft3: 40 },
      { key: "bedrooms:divan-bed-double-and-mattress", title: "Divan bed double and mattress", ft3: 55 },
      { key: "bedrooms:divan-bed-king-and-mattress", title: "Divan bed king and mattress", ft3: 60 },
      { key: "bedrooms:divan-bed-super-king-and-mattress", title: "Divan bed super-king and mattress", ft3: 72 },
      { key: "bedrooms:frame-single-and-mattress", title: "Frame single and mattress", ft3: 25 },
      { key: "bedrooms:frame-double-and-mattress", title: "Frame double and mattress", ft3: 40 },
      { key: "bedrooms:frame-king-and-mattress", title: "Frame king and mattress", ft3: 45 },
      { key: "bedrooms:frame-super-king-and-mattress", title: "Frame super king and mattress", ft3: 52 },
      { key: "bedrooms:single-mattress", title: "Single mattress", ft3: 21 },
      { key: "bedrooms:double-mattress", title: "Double mattress", ft3: 55 },
      { key: "bedrooms:king-size-mattress", title: "King size mattress", ft3: 75 },
      { key: "bedrooms:small-child-s-bed", title: "Small child's bed", ft3: 30 },
      { key: "bedrooms:bunk-bed", title: "Bunk bed", ft3: 70 },
      { key: "bedrooms:cot", title: "Cot", ft3: 10 },
      { key: "bedrooms:futon", title: "Futon", ft3: 30 },
      { key: "bedrooms:bedside-table", title: "Bedside table", ft3: 5 },
      { key: "bedrooms:chest-of-drawers-small", title: "Chest of drawers small", ft3: 18 },
      { key: "bedrooms:chest-of-drawers-medium", title: "Chest of drawers medium", ft3: 25 },
      { key: "bedrooms:chest-of-drawers-large", title: "Chest of drawers large", ft3: 40 },
      { key: "bedrooms:tall-boy", title: "Tall boy", ft3: 23 },
      { key: "bedrooms:dressing-table", title: "Dressing table", ft3: 25 },
      { key: "bedrooms:wardrobe-single", title: "Wardrobe single", ft3: 25 },
      { key: "bedrooms:wardrobe-double", title: "Wardrobe double", ft3: 40 },
      { key: "bedrooms:wardrobe-triple", title: "Wardrobe triple", ft3: 60 },
      { key: "bedrooms:occasional-chair", title: "Occasional chair", ft3: 12 },
      { key: "bedrooms:chaise-longue", title: "Chaise longue", ft3: 25 },
      { key: "bedrooms:trunk-blanket-box", title: "Trunk/blanket box", ft3: 8 },
      { key: "bedrooms:clothes-basket", title: "Clothes basket", ft3: 5 },
      { key: "bedrooms:picture-mirror-small", title: "Picture/mirror small", ft3: 1 },
      { key: "bedrooms:picture-mirror-medium", title: "Picture/mirror medium", ft3: 3 },
      { key: "bedrooms:picture-mirror-large", title: "Picture/mirror large", ft3: 5 },
      { key: "bedrooms:indoor-plant", title: "Indoor plant", ft3: 8 },
      { key: "bedrooms:toy-kitchen", title: "Toy Kitchen", ft3: 9 },
      { key: "bedrooms:dolls-house", title: "Dolls house", ft3: 13 },
      { key: "bedrooms:sundry-cuft", title: "Sundry cuft", ft3: 1 },
      { key: "bedrooms:wardrobe-box", title: "Wardrobe box", ft3: 6 },
      { key: "bedrooms:boxed-already", title: "Boxed Already", ft3: 3 },
      { key: "bedrooms:medium-box", title: "Medium box", ft3: 2 },
      { key: "bedrooms:large-box", title: "Large box", ft3: 4 },
    ],
  },
  {
    key: "garage-garden-area",
    title: "Garage / garden area",
    items: [
      { key: "garage-garden-area:single-garage-half", title: "Single garage (half)", ft3: 400 },
      { key: "garage-garden-area:single-garage-full", title: "Single garage (full)", ft3: 800 },
      { key: "garage-garden-area:6x4-shed-full", title: "6x4 shed (full)", ft3: 140 },
      { key: "garage-garden-area:12x8-shed-full", title: "12x8 shed (full)", ft3: 280 },
      { key: "garage-garden-area:garden-table", title: "Garden table", ft3: 25 },
      { key: "garage-garden-area:garden-chairs", title: "Garden chairs", ft3: 10 },
      { key: "garage-garden-area:garden-lounger", title: "Garden lounger", ft3: 20 },
      { key: "garage-garden-area:garden-bench", title: "Garden bench", ft3: 25 },
      { key: "garage-garden-area:picnic-table", title: "Picnic table", ft3: 60 },
      { key: "garage-garden-area:bbq-small", title: "BBQ small", ft3: 18 },
      { key: "garage-garden-area:bbq-medium", title: "BBQ medium", ft3: 32 },
      { key: "garage-garden-area:bbq-large", title: "BBQ large", ft3: 45 },
      { key: "garage-garden-area:parasol", title: "Parasol", ft3: 18 },
      { key: "garage-garden-area:gas-heater", title: "Gas heater", ft3: 18 },
      { key: "garage-garden-area:stacking-chairs", title: "Stacking chairs", ft3: 3 },
      { key: "garage-garden-area:folding-chairs", title: "Folding chairs", ft3: 3 },
      { key: "garage-garden-area:trampoline", title: "Trampoline", ft3: 70 },
      { key: "garage-garden-area:netball-post", title: "Netball Post", ft3: 18 },
      { key: "garage-garden-area:climbing-frame-large", title: "Climbing frame large", ft3: 175 },
      { key: "garage-garden-area:swing-single", title: "Swing single", ft3: 25 },
      { key: "garage-garden-area:slide", title: "Slide", ft3: 20 },
      { key: "garage-garden-area:plastic-wendy-house", title: "Plastic Wendy house", ft3: 40 },
      { key: "garage-garden-area:garden-storage-unit", title: "Garden Storage Unit", ft3: 18 },
      { key: "garage-garden-area:garden-hose", title: "Garden hose", ft3: 2 },
      { key: "garage-garden-area:outdoor-bin", title: "Outdoor bin", ft3: 12 },
      { key: "garage-garden-area:wheelbarrow", title: "Wheelbarrow", ft3: 14 },
      { key: "garage-garden-area:storage-racking", title: "Storage Racking", ft3: 26 },
      { key: "garage-garden-area:electric-mower", title: "Electric mower", ft3: 14 },
      { key: "garage-garden-area:petrol-mower", title: "Petrol mower", ft3: 18 },
      { key: "garage-garden-area:ride-on-mower", title: "Ride on mower", ft3: 125 },
      { key: "garage-garden-area:strimmer", title: "Strimmer", ft3: 5 },
      { key: "garage-garden-area:sundry-cuft", title: "Sundry cuft", ft3: 1 },
      { key: "garage-garden-area:bike", title: "Bike", ft3: 10 },
      { key: "garage-garden-area:child-s-bike", title: "Child's bike", ft3: 6 },
      { key: "garage-garden-area:step-ladder", title: "Step ladder", ft3: 8 },
      { key: "garage-garden-area:ladder", title: "Ladder", ft3: 18 },
      { key: "garage-garden-area:workbench", title: "Workbench", ft3: 20 },
      { key: "garage-garden-area:tool-cabinet-wheeled", title: "Tool cabinet wheeled", ft3: 16 },
      { key: "garage-garden-area:car-roof-box", title: "Car roof box", ft3: 16 },
      { key: "garage-garden-area:golf-clubs", title: "Golf clubs", ft3: 3 },
      { key: "garage-garden-area:multi-gym-weights-machine", title: "Multi gym Weights machine", ft3: 120 },
      { key: "garage-garden-area:running-machine-folded", title: "Running machine folded", ft3: 50 },
      { key: "garage-garden-area:exercise-bike", title: "Exercise bike", ft3: 38 },
      { key: "garage-garden-area:table-tennis-table", title: "Table tennis table", ft3: 50 },
      { key: "garage-garden-area:canoe", title: "Canoe", ft3: 28 },
      { key: "garage-garden-area:pushchair", title: "Pushchair", ft3: 6 },
      { key: "garage-garden-area:bag-of-chopped-woods", title: "Bag of Chopped woods", ft3: 15 },
      { key: "garage-garden-area:outdoor-plant-small", title: "Outdoor plant small", ft3: 4 },
      { key: "garage-garden-area:outdoor-plant-medium", title: "Outdoor plant medium", ft3: 12 },
      { key: "garage-garden-area:outdoor-plant-large", title: "Outdoor plant large", ft3: 20 },
      { key: "garage-garden-area:already-boxed", title: "Already boxed", ft3: 3 },
      { key: "garage-garden-area:medium-box", title: "Medium box", ft3: 2 },
      { key: "garage-garden-area:large-box", title: "Large box", ft3: 4 },
    ],
  },
  {
    key: "kitchen-and-utility",
    title: "Kitchen and utility",
    items: [
      { key: "kitchen-and-utility:fridge-freezer", title: "Fridge freezer", ft3: 50 },
      { key: "kitchen-and-utility:medium-fridge", title: "Medium fridge", ft3: 13 },
      { key: "kitchen-and-utility:fridge-freezer-american", title: "Fridge freezer American", ft3: 80 },
      { key: "kitchen-and-utility:chest-freezer", title: "Chest freezer", ft3: 70 },
      { key: "kitchen-and-utility:washing-machine", title: "Washing machine", ft3: 13 },
      { key: "kitchen-and-utility:tumble-dryer", title: "Tumble dryer", ft3: 13 },
      { key: "kitchen-and-utility:dishwasher", title: "Dishwasher", ft3: 22 },
      { key: "kitchen-and-utility:microwave", title: "Microwave", ft3: 6 },
      { key: "kitchen-and-utility:cooker-single", title: "Cooker single", ft3: 16 },
      { key: "kitchen-and-utility:cooker-large", title: "Cooker large", ft3: 22 },
      { key: "kitchen-and-utility:cooker-range", title: "Cooker range", ft3: 32 },
      { key: "kitchen-and-utility:table-and-2-breakfast-chairs", title: "Table and 2 breakfast chairs", ft3: 15 },
      { key: "kitchen-and-utility:breakfast-chair", title: "Breakfast chair", ft3: 5 },
      { key: "kitchen-and-utility:kitchen-cabinet", title: "Kitchen cabinet", ft3: 25 },
      { key: "kitchen-and-utility:baby-high-chair", title: "Baby high chair", ft3: 8 },
      { key: "kitchen-and-utility:air-con-unit", title: "Air con unit", ft3: 10 },
      { key: "kitchen-and-utility:bin", title: "Bin", ft3: 3 },
      { key: "kitchen-and-utility:ironing-board", title: "Ironing board", ft3: 2 },
      { key: "kitchen-and-utility:indoor-plant", title: "Indoor plant", ft3: 8 },
      { key: "kitchen-and-utility:picture-mirror-small", title: "Picture/mirror small", ft3: 1 },
      { key: "kitchen-and-utility:picture-mirror-medium", title: "Picture/mirror medium", ft3: 3 },
      { key: "kitchen-and-utility:picture-mirror-large", title: "Picture/mirror large", ft3: 5 },
      { key: "kitchen-and-utility:sundry-cuft", title: "Sundry cuft", ft3: 1 },
      { key: "kitchen-and-utility:already-boxed", title: "Already boxed", ft3: 3 },
      { key: "kitchen-and-utility:medium-box", title: "Medium box", ft3: 2 },
      { key: "kitchen-and-utility:large-box", title: "Large box", ft3: 4 },
    ],
  },
  {
    key: "office-and-commercial",
    title: "Office and commercial",
    items: [
      { key: "office-and-commercial:office-desk", title: "Office desk", ft3: 45 },
      { key: "office-and-commercial:pedestal-desk", title: "Pedestal desk", ft3: 4 },
      { key: "office-and-commercial:meeting-table", title: "Meeting table", ft3: 160 },
      { key: "office-and-commercial:desk-chairs", title: "Desk chairs", ft3: 10 },
      { key: "office-and-commercial:office-chair", title: "Office chair", ft3: 7 },
      { key: "office-and-commercial:filing-cabinet-2-drawers", title: "Filing cabinet 2 drawers", ft3: 10 },
      { key: "office-and-commercial:filing-cabinet-4-drawer", title: "Filing cabinet 4 drawer", ft3: 20 },
      { key: "office-and-commercial:monitor", title: "Monitor", ft3: 1 },
      { key: "office-and-commercial:laptop", title: "Laptop", ft3: 1 },
      { key: "office-and-commercial:desktop-computer", title: "Desktop computer", ft3: 8 },
      { key: "office-and-commercial:printer", title: "Printer", ft3: 4 },
      { key: "office-and-commercial:printer-large", title: "Printer large", ft3: 6 },
      { key: "office-and-commercial:photocopier", title: "Photocopier", ft3: 60 },
      { key: "office-and-commercial:server-cabinet-medium", title: "Server cabinet medium", ft3: 12 },
      { key: "office-and-commercial:storage-unit", title: "Storage unit", ft3: 50 },
      { key: "office-and-commercial:fan", title: "Fan", ft3: 5 },
      { key: "office-and-commercial:sundry-cuft", title: "Sundry cuft", ft3: 1 },
      { key: "office-and-commercial:boxed-already", title: "Boxed already", ft3: 3 },
      { key: "office-and-commercial:medium-box", title: "Medium box", ft3: 2 },
      { key: "office-and-commercial:large-box", title: "Large box", ft3: 4 },
    ],
  },
];

const byKey = new Map<string, CubicCatalogueItem>();
for (const c of CUBIC_CATEGORIES) for (const i of c.items) byKey.set(i.key, i);

export function catalogueItem(key: string): CubicCatalogueItem | undefined {
  return byKey.get(key);
}

export const CUBIC_CATEGORY_TITLES: Record<string, string> = Object.fromEntries(
  CUBIC_CATEGORIES.map((c) => [c.key, c.title]),
);
